/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.merge.Dashboard.Admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class addDosen extends javax.swing.JFrame {

    
    private static final String DB_URL = "jdbc:mysql://localhost:3306/data-quiz";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "";
    /**
     * Creates new form addMahasiswa
     */
    public addDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nipDosen = new javax.swing.JTextField();
        emailDosen = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        alamatDosen = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        tanggalLahirDosen = new javax.swing.JTextField();
        emailLabel3 = new javax.swing.JLabel();
        telefonDosen = new javax.swing.JTextField();
        emailLabel4 = new javax.swing.JLabel();
        Edit = new java.awt.Button();
        usernameDosen = new javax.swing.JTextField();
        namaLabel1 = new javax.swing.JLabel();
        passwordDosen = new javax.swing.JTextField();
        namaLabel2 = new javax.swing.JLabel();
        namaLabel3 = new javax.swing.JLabel();
        namaDosen = new javax.swing.JTextField();
        genderLakiLaki = new javax.swing.JRadioButton();
        genderPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(835, 488));
        setSize(new java.awt.Dimension(835, 488));

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));

        WelcomeText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeText.setText("Tambah Dosen");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(WelcomeText)
                .addContainerGap(619, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeText)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        namaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        namaLabel.setText("NIP");

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("Email");

        nipDosen.setText("nip Dosen");
        nipDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nipDosenActionPerformed(evt);
            }
        });

        emailDosen.setText("email Dosen");

        emailLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel1.setText("Alamat");

        alamatDosen.setText("alamat Dosen");
        alamatDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatDosenActionPerformed(evt);
            }
        });

        emailLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel2.setText("Tanggal Lahir");

        tanggalLahirDosen.setText("tanggal Lahir Dosen");

        emailLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel3.setText("Gender");

        telefonDosen.setText("telefon Dosen");

        emailLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel4.setText("Telefon");

        Edit.setBackground(new java.awt.Color(0, 0, 153));
        Edit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setLabel("Tambah Dosen");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        usernameDosen.setText("Username Dosen");

        namaLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        namaLabel1.setText("Username");

        passwordDosen.setText("Password Dosen");
        passwordDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordDosenActionPerformed(evt);
            }
        });

        namaLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        namaLabel2.setText("Password");

        namaLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        namaLabel3.setText("Nama");

        namaDosen.setText("nama Dosen");

        genderLakiLaki.setText("Laki-Laki");

        genderPerempuan.setText("Perempuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(namaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(passwordDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(usernameDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailDosen)
                            .addComponent(nipDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatDosen)
                            .addComponent(tanggalLahirDosen)
                            .addComponent(telefonDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderLakiLaki)
                                .addGap(18, 18, 18)
                                .addComponent(genderPerempuan)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel1)
                    .addComponent(usernameDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel2)
                    .addComponent(passwordDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel3)
                    .addComponent(namaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(nipDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1)
                    .addComponent(alamatDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(tanggalLahirDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel3)
                    .addComponent(genderLakiLaki)
                    .addComponent(genderPerempuan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel4)
                    .addComponent(telefonDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        try {
            String newUsername = usernameDosen.getText();
            String newPassword = passwordDosen.getText();
            String newName = namaDosen.getText();
            String newNIM = nipDosen.getText();
            String newEmail = emailDosen.getText();
            String newAlamat = alamatDosen.getText();
            String newBirthDate = tanggalLahirDosen.getText();
            String newGender = getSelectedGender();
            String telefonString = telefonDosen.getText();
            int newisLoggedIn = 0;

            telefonString = telefonString.replaceAll("[^0-9]", "");

            int newPhoneNumber = Integer.parseInt(telefonString);

            try (Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                String insertQuery = "INSERT INTO `data-dosen` (usernameDosen, passwordDosen, namaDosen, nipDosen, emailDosen, alamatDosen, tanggalLahirDosen, genderDosen, telefon, isLoggedIn) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                try (PreparedStatement insertStatement = connection.prepareStatement(insertQuery)) {
                    insertStatement.setString(1, newUsername);
                    insertStatement.setString(2, newPassword);
                    insertStatement.setString(3, newName);
                    insertStatement.setString(4, newNIM);
                    insertStatement.setString(5, newEmail);
                    insertStatement.setString(6, newAlamat);
                    insertStatement.setString(7, newBirthDate);
                    insertStatement.setString(8, newGender);
                    insertStatement.setInt(9, newPhoneNumber);
                    insertStatement.setInt(10, newisLoggedIn);

                    int rowsInserted = insertStatement.executeUpdate();

                    if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(this, "Data berhasil dimasukkan");
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal memasukkan data");
                    }
                }
            }
        } catch (SQLException | NumberFormatException e) {
            e.printStackTrace();
        }


        Dashboard_Quiz_Admin dqa = new Dashboard_Quiz_Admin();
        dqa.show();
        dispose();
    }//GEN-LAST:event_EditActionPerformed

    private void alamatDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatDosenActionPerformed

    private void passwordDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordDosenActionPerformed

    private void nipDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nipDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nipDosenActionPerformed

    private String getSelectedGender() {
        if (genderLakiLaki.isSelected()) {
            return "Laki-Laki";
        } else if (genderPerempuan.isSelected()) {
            return "Perempuan";
        } else {
            return ""; // Atau dapat diatasi sesuai kebutuhan, misalnya dengan mengembalikan null atau nilai default lainnya.
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Edit;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JTextField alamatDosen;
    private javax.swing.JTextField emailDosen;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel emailLabel3;
    private javax.swing.JLabel emailLabel4;
    private javax.swing.JRadioButton genderLakiLaki;
    private javax.swing.JRadioButton genderPerempuan;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField namaDosen;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel1;
    private javax.swing.JLabel namaLabel2;
    private javax.swing.JLabel namaLabel3;
    private javax.swing.JTextField nipDosen;
    private javax.swing.JTextField passwordDosen;
    private javax.swing.JTextField tanggalLahirDosen;
    private javax.swing.JTextField telefonDosen;
    private javax.swing.JTextField usernameDosen;
    // End of variables declaration//GEN-END:variables
}
