/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.merge.Dashboard.Admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class addMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form addMahasiswa
     */
    private static final String DB_URL = "jdbc:mysql://localhost:3306/data-quiz";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "";
    public addMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameMahasiswa = new javax.swing.JTextField();
        passwordMahasiswa = new javax.swing.JTextField();
        namaMahasiswa = new javax.swing.JTextField();
        emailMahasiswa = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        alamatMahasiswa = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        tanggalLahirMahasiswa = new javax.swing.JTextField();
        emailLabel3 = new javax.swing.JLabel();
        telefonMahasiswa = new javax.swing.JTextField();
        emailLabel4 = new javax.swing.JLabel();
        tambahMahasiswa = new java.awt.Button();
        genderLakiLaki = new javax.swing.JRadioButton();
        genderPerempuan = new javax.swing.JRadioButton();
        nimMahasiswa = new javax.swing.JTextField();
        nimLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(835, 560));
        setPreferredSize(new java.awt.Dimension(835, 488));
        setSize(new java.awt.Dimension(835, 488));

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));

        WelcomeText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeText.setText("Tambah Mahasiswa");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(WelcomeText)
                .addContainerGap(565, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeText)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        namaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        namaLabel.setText("Nama");

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("Email");

        usernameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setText("Password");

        usernameMahasiswa.setText("username Mahasiswa");
        usernameMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameMahasiswaActionPerformed(evt);
            }
        });

        passwordMahasiswa.setText("password Mahasiswa");
        passwordMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordMahasiswaActionPerformed(evt);
            }
        });

        namaMahasiswa.setText("nama Mahasiswa");

        emailMahasiswa.setText("email Mahasiswa");

        emailLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel1.setText("Alamat");

        alamatMahasiswa.setText("alamat Mahasiswa");
        alamatMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatMahasiswaActionPerformed(evt);
            }
        });

        emailLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel2.setText("Tanggal Lahir");

        tanggalLahirMahasiswa.setText("tanggal Lahir Mahasiswa");

        emailLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel3.setText("Gender");

        telefonMahasiswa.setText("telefon Mahasiswa");

        emailLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel4.setText("Telefon");

        tambahMahasiswa.setBackground(new java.awt.Color(0, 0, 153));
        tambahMahasiswa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tambahMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        tambahMahasiswa.setLabel("Tambah Mahasiswa");
        tambahMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMahasiswaActionPerformed(evt);
            }
        });

        genderLakiLaki.setText("Laki-laki");
        genderLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderLakiLakiActionPerformed(evt);
            }
        });

        genderPerempuan.setText("Perempuan");
        genderPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderPerempuanActionPerformed(evt);
            }
        });

        nimMahasiswa.setText("nim Mahasiswa");

        nimLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nimLabel.setText("NIM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordMahasiswa)
                            .addComponent(usernameMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tambahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(nimMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailMahasiswa)
                                .addComponent(namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alamatMahasiswa)
                                .addComponent(tanggalLahirMahasiswa)
                                .addComponent(telefonMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(genderLakiLaki)
                                    .addGap(18, 18, 18)
                                    .addComponent(genderPerempuan))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimLabel)
                    .addComponent(nimMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1)
                    .addComponent(alamatMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(tanggalLahirMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel3)
                    .addComponent(genderLakiLaki)
                    .addComponent(genderPerempuan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel4)
                    .addComponent(telefonMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(tambahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMahasiswaActionPerformed
        // TODO add your handling code here:
        try {
            String newUsername = usernameMahasiswa.getText();
            String newPassword = passwordMahasiswa.getText();
            String newName = namaMahasiswa.getText();
            String newNIM = nimMahasiswa.getText();
            String newEmail = emailMahasiswa.getText();
            String newAlamat = alamatMahasiswa.getText();
            String newBirthDate = tanggalLahirMahasiswa.getText();
            String newGender = getSelectedGender();
            String newPhoneNumber = telefonMahasiswa.getText();

            Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);

            String insertQuery = "INSERT INTO `data-mahasiswa` (username, password, nama, nim, email, alamat, `tanggal-lahir`, gender, telefon) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (PreparedStatement insertStatement = connection.prepareStatement(insertQuery)) {
                insertStatement.setString(1, newUsername);
                insertStatement.setString(2, newPassword);
                insertStatement.setString(3, newName);
                insertStatement.setString(4, newNIM);
                insertStatement.setString(5, newEmail);
                insertStatement.setString(6, newAlamat);
                insertStatement.setString(7, newBirthDate);
                insertStatement.setString(8, newGender);
                insertStatement.setString(9, newPhoneNumber);

                int rowsInserted = insertStatement.executeUpdate();

                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil ditambahkan");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data mahasiswa");
                }
            }

            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        Dashboard_Quiz_Admin dqa = new Dashboard_Quiz_Admin();
        dqa.show();
        dispose();
    }//GEN-LAST:event_tambahMahasiswaActionPerformed

    private void alamatMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatMahasiswaActionPerformed

    private void usernameMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameMahasiswaActionPerformed

    private void passwordMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordMahasiswaActionPerformed

    private void genderLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderLakiLakiActionPerformed

    }//GEN-LAST:event_genderLakiLakiActionPerformed

    private void genderPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderPerempuanActionPerformed

    }//GEN-LAST:event_genderPerempuanActionPerformed

    
    private String getSelectedGender() {
        if (genderLakiLaki.isSelected()) {
            return "Laki-Laki";
        } else if (genderPerempuan.isSelected()) {
            return "Perempuan";
        } else {
            return ""; // Atau dapat diatasi sesuai kebutuhan, misalnya dengan mengembalikan null atau nilai default lainnya.
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JTextField alamatMahasiswa;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel emailLabel3;
    private javax.swing.JLabel emailLabel4;
    private javax.swing.JTextField emailMahasiswa;
    private javax.swing.JRadioButton genderLakiLaki;
    private javax.swing.JRadioButton genderPerempuan;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaMahasiswa;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimMahasiswa;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordMahasiswa;
    private java.awt.Button tambahMahasiswa;
    private javax.swing.JTextField tanggalLahirMahasiswa;
    private javax.swing.JTextField telefonMahasiswa;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameMahasiswa;
    // End of variables declaration//GEN-END:variables
}
