/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard.Student;

/**
 *
 * @author Lenovo
 */
public class Profile_Mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Profile_Mahasiswa
     */
    public Profile_Mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubahDataDialog = new javax.swing.JDialog();
        tidakButton = new javax.swing.JButton();
        yaButton = new javax.swing.JButton();
        ubahDataLabel = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        Edit = new java.awt.Button();
        WelcomeText = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        namaMahasiswa = new javax.swing.JTextField();
        emailMahasiswa = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        alamatMahasiswa = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        tanggalLahirMahasiswa = new javax.swing.JTextField();
        emailLabel3 = new javax.swing.JLabel();
        genderMahasiswa = new javax.swing.JTextField();
        telefonMahasiswa = new javax.swing.JTextField();
        emailLabel4 = new javax.swing.JLabel();

        ubahDataDialog.setLocation(new java.awt.Point(150, 140));
        ubahDataDialog.setMinimumSize(new java.awt.Dimension(438, 220));

        tidakButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tidakButton.setText("Tidak");
        tidakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakButtonActionPerformed(evt);
            }
        });

        yaButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yaButton.setText("Ya");
        yaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaButtonActionPerformed(evt);
            }
        });

        ubahDataLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ubahDataLabel.setText("Anda Yakin Mengubah Data?");

        javax.swing.GroupLayout ubahDataDialogLayout = new javax.swing.GroupLayout(ubahDataDialog.getContentPane());
        ubahDataDialog.getContentPane().setLayout(ubahDataDialogLayout);
        ubahDataDialogLayout.setHorizontalGroup(
            ubahDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahDataDialogLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(ubahDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubahDataLabel)
                    .addGroup(ubahDataDialogLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(yaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tidakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        ubahDataDialogLayout.setVerticalGroup(
            ubahDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahDataDialogLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(ubahDataLabel)
                .addGap(18, 18, 18)
                .addGroup(ubahDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaButton)
                    .addComponent(tidakButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(794, 442));

        headerPanel.setBackground(new java.awt.Color(0, 0, 153));

        Edit.setBackground(new java.awt.Color(204, 204, 204));
        Edit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Edit.setForeground(new java.awt.Color(0, 0, 153));
        Edit.setLabel("Save");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        WelcomeText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeText.setText("Profil");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(WelcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeText)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        namaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        namaLabel.setText("Nama");

        emailLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel.setText("Email");

        namaMahasiswa.setText("namaMahasiswa");

        emailMahasiswa.setText("emailMahasiswa");

        emailLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel1.setText("Alamat");

        alamatMahasiswa.setText("alamatMahasiswa");
        alamatMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatMahasiswaActionPerformed(evt);
            }
        });

        emailLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel2.setText("Tanggal Lahir");

        tanggalLahirMahasiswa.setText("tanggalLahirMahasiswa");

        emailLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel3.setText("Gender");

        genderMahasiswa.setText("genderMahasiswa");

        telefonMahasiswa.setText("telefonMahasiswa");

        emailLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailLabel4.setText("Telefon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailMahasiswa)
                    .addComponent(namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatMahasiswa)
                    .addComponent(tanggalLahirMahasiswa)
                    .addComponent(genderMahasiswa)
                    .addComponent(telefonMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1)
                    .addComponent(alamatMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(tanggalLahirMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel3)
                    .addComponent(genderMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel4)
                    .addComponent(telefonMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        ubahDataDialog.setVisible(true);
    }//GEN-LAST:event_EditActionPerformed

    private void alamatMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatMahasiswaActionPerformed

    private void yaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaButtonActionPerformed
        // TODO add your handling code here:
        Dashboard_Quiz_Student dqs = new Dashboard_Quiz_Student();
        dqs.show();
        dispose();
    }//GEN-LAST:event_yaButtonActionPerformed

    private void tidakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakButtonActionPerformed
        ubahDataDialog.setVisible(false);
    }//GEN-LAST:event_tidakButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Edit;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JTextField alamatMahasiswa;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel emailLabel3;
    private javax.swing.JLabel emailLabel4;
    private javax.swing.JTextField emailMahasiswa;
    private javax.swing.JTextField genderMahasiswa;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaMahasiswa;
    private javax.swing.JTextField tanggalLahirMahasiswa;
    private javax.swing.JTextField telefonMahasiswa;
    private javax.swing.JButton tidakButton;
    private javax.swing.JDialog ubahDataDialog;
    private javax.swing.JLabel ubahDataLabel;
    private javax.swing.JButton yaButton;
    // End of variables declaration//GEN-END:variables
}
