/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.merge.login;
import java.sql.*;
import javax.swing.*;
import pkgfinal.merge.Dashboard.Admin.*;
import pkgfinal.merge.Dashboard.Lecturer.*;
import pkgfinal.merge.Dashboard.Student.*;


/**
 *
 * @author Mikail
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    static final String DB_URL = "jdbc:mysql://127.0.0.1:3306/data-quiz";
    static final String DB_USER = "root";
    static final String DB_PASS = "";
    
    Dashboard_Quiz_Student dqs = new Dashboard_Quiz_Student();
    Dashboard_Quiz_Lecturer dql = new Dashboard_Quiz_Lecturer();
    Dashboard_Quiz_Admin dqa = new Dashboard_Quiz_Admin();
    
    
    public Login() {
        initComponents();
        jTextField1.setText("");
        jPasswordField1.setText("");
    }
    
    public boolean loginController(String inputUsername, String inputPassword) {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    try {
        conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
        
        String queryMahasiswa = "SELECT username, password FROM `data-mahasiswa` WHERE username=? AND password=?";
        ps = conn.prepareStatement(queryMahasiswa);
        ps.setString(1, inputUsername);
        ps.setString(2, inputPassword);
        rs = ps.executeQuery();

        if (rs.next()) {
            String storedPassword = rs.getString("password");
            if (inputPassword.equals(storedPassword)) {
                String updateQuery = "UPDATE `data-mahasiswa` SET isLoggedIn=?";
                try (PreparedStatement updateStatement = conn.prepareStatement(updateQuery)) {
                    updateStatement.setString(1, "1");
                    updateStatement.executeUpdate();
                }
                return true;
            }
        }

        String queryAdmin = "SELECT usernameAdmin, passwordAdmin FROM `data-admin` WHERE usernameAdmin=? AND passwordAdmin=?";
        ps = conn.prepareStatement(queryAdmin);
        ps.setString(1, inputUsername);
        ps.setString(2, inputPassword);
        rs = ps.executeQuery();

        if (rs.next()) {
            String storedPassword = rs.getString("passwordAdmin");
            if (inputPassword.equals(storedPassword)) {
                String updateQuery = "UPDATE `data-admin` SET isLoggedIn=?";
                try (PreparedStatement updateStatement = conn.prepareStatement(updateQuery)) {
                    updateStatement.setString(1, "1");
                    updateStatement.executeUpdate();
                }
                return true;
            }
        }

        String queryDosen = "SELECT usernameDosen, passwordDosen FROM `data-dosen` WHERE usernameDosen=? AND passwordDosen=?";
        ps = conn.prepareStatement(queryDosen);
        ps.setString(1, inputUsername);
        ps.setString(2, inputPassword);
        rs = ps.executeQuery();

        if (rs.next()) {
            String storedPassword = rs.getString("passwordDosen");
            if (inputPassword.equals(storedPassword)) {
                String updateQuery = "UPDATE `data-dosen` SET isLoggedIn=?";
                try (PreparedStatement updateStatement = conn.prepareStatement(updateQuery)) {
                    updateStatement.setString(1, "1");
                    updateStatement.executeUpdate();
                }
                return true;
            }
        }

        return false;
    } catch (SQLException e) {
        e.printStackTrace();
        return false;
    } finally {
        try {
            if (rs != null) {
                rs.close();
            }
            if (ps != null) {
                ps.close();
            }
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Quiz");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            if (loginController(jTextField1.getText(), jPasswordField1.getText())) {
                conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);

                String queryMahasiswa = "SELECT nim FROM `data-mahasiswa` WHERE username=?";
                ps = conn.prepareStatement(queryMahasiswa);
                ps.setString(1, jTextField1.getText());
                rs = ps.executeQuery();

                if (rs.next()) {
                    rs.getString("nim");
                    dqs.show();
                    dispose();
                }

                String queryDosen = "SELECT nipDosen FROM `data-dosen` WHERE usernameDosen=?";
                ps = conn.prepareStatement(queryDosen);
                ps.setString(1, jTextField1.getText());
                rs = ps.executeQuery();

                if (rs.next()) {
                    rs.getString("nipDosen");
                    dql.show();
                    dispose();
                }

                String queryAdmin = "SELECT nipAdmin FROM `data-admin` WHERE usernameAdmin=?";
                ps = conn.prepareStatement(queryAdmin);
                ps.setString(1, jTextField1.getText());
                rs = ps.executeQuery();

                if (rs.next()) {
                    rs.getString("nipAdmin");
                    dqa.show();
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Login!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
